language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x

before_install:
  - go get -t -v ./...

install:
  - get github.com/go-netty/go-netty

script:
  - go test -coverprofile=coverage.txt -covermode=atomic -bench .

after_success:
  - bash <(curl -s https://codecov.io/bash)
